import 'dotenv/config';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import { loadCore } from './dataStore.js';
import { getGraph, getGraphNodes, getNodeGraph, getProductGraph, getRelationship, getRelationships } from './graphEngine.js';
import { recommendProductsV1 } from './recommendationEngine.js';
import { getProductBundle, recommendProducts } from './relationshipEngine.js';
import { productPagePayload } from './pageGenerator.js';
const app = Fastify({ logger: true });
await app.register(cors, { origin: true });
app.addHook('preHandler', async (req, reply) => {
  const key = process.env.MDS_CORE_API_KEY;
  if (key && key !== 'change-me' && req.headers['x-api-key'] !== key) reply.code(401).send({ error: 'Unauthorized' });
});
const productGraphRoute = async (req:any) => getProductGraph(await loadCore(), req.params.slug) ?? { error:'Not found' };
app.get('/health', async () => ({ ok: true, service: 'mds-core' }));
app.get('/products/:slug', async (req:any) => getProductBundle(await loadCore(), req.params.slug) ?? { error:'Not found' });
app.get('/pages/product/:slug', async (req:any) => productPagePayload(await loadCore(), req.params.slug) ?? { error:'Not found' });
app.get('/api/graph', async () => getGraph(await loadCore()));
app.get('/api/graph/nodes', async (req:any) => getGraphNodes(await loadCore(), req.query || {}));
app.get('/api/graph/nodes/:type', async (req:any) => getGraphNodes(await loadCore(), { type: req.params.type }));
app.get('/api/graph/nodes/:type/:id', async (req:any) => getNodeGraph(await loadCore(), req.params.type, req.params.id) ?? { error:'Not found' });
app.get('/api/graph/relationships', async (req:any) => getRelationships(await loadCore(), req.query || {}));
app.get('/api/graph/relationships/:id', async (req:any) => getRelationship(await loadCore(), req.params.id) ?? { error:'Not found' });
app.get('/api/graph/products/:slug', productGraphRoute);
app.get('/graph', async () => getGraph(await loadCore()));
app.get('/graph/relationships', async (req:any) => getRelationships(await loadCore(), req.query || {}));
app.get('/graph/products/:slug', productGraphRoute);
app.get('/graph/nodes/:type/:id', async (req:any) => getNodeGraph(await loadCore(), req.params.type, req.params.id) ?? { error:'Not found' });
app.post('/api/recommendations/v1', async (req:any) => recommendProductsV1(await loadCore(), req.body || {}));
app.post('/recommend', async (req:any) => recommendProducts(await loadCore(), req.body || {}));
const port = Number(process.env.PORT || 8787);
app.listen({ port, host: '0.0.0.0' });
